/*
 * This source file was generated by the Gradle 'init' task
 */

package coursepapper;
import java.util.Scanner;

import main.java.coursepapper.Employee;
import main.java.coursepapper.EmployeeBook;

public class App {

    public static void main(String[] args) {
        int id = 0;
        System.out.println(
            "what do you want??!\n"+
            "1 - Получить список всех сотрудников\n"+
            "2 - Посчитать сумму затрат на ЗП\n"+
            "3 - Найти сотрудника с минимальной ЗП\n"+
            "4 - Найти сотрудника с максимальной ЗП\n"+
            "5 - Подсчитать среднее значение зарплат\n"+
            "6 - Добавить сотрудника\n"+
            "7 - Удалить сотрудника\n"
        );
        Scanner scan = new Scanner(System.in);
        int choose = Integer.parseInt(scan.nextLine());
        switch (choose) {
            case 1:
                EmployeeBook.getAllEmployees();
                break;
            case 6:
                Employee.createEmployee(id);
                break;
            default:
                break;
        }
        scan.close();
    }
}
