/*
 * This source file was generated by the Gradle 'init' task
 */

package coursepapper;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        System.out.println(
            "what do you want??!\n"+
            "1 - Получить список всех сотрудников\n"+
            "2 - Посчитать сумму затрат на ЗП\n"+
            "3 - Найти сотрудника с минимальной ЗП\n"+
            "4 - Найти сотрудника с максимальной ЗП\n"+
            "5 - Подсчитать среднее значение зарплат\n"+
            "6 - Добавить сотрудника\n"+
            "7 - Удалить сотрудника\n"
        );
        Scanner scan = new Scanner(System.in);
        int choose = Integer.parseInt(scan.nextLine());
        scan.close();
        switch (choose) {
            case 1:
                
                break;
        
            default:
                break;
        }
    }
}
